[package]
name = "dmarc-rs"
version = "0.1.0"
edition = "2021"
authors = ["Ollivier Robert <roberto@keltia.net>"]
keywords = ["dmarc", "reporting", "e-mail", "cli", "cli-utility"]
repository = "https://github.com/keltia/dmarc-rs"
license = "MIT"
readme = "README.md"
description = "Rust utility to decode and display DMARC reports."
documentation = "https://docs.rs/dmarc-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive", "cargo"] }
log = "0.4"
stderrlog = "0.5.1"
